# Generated by Django 5.0.3 on 2024-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.CharField(max_length=10)),
                ('book_img', models.ImageField(upload_to='book_img/')),
            ],
            options={
                'db_table': 'bookstore',
            },
        ),
    ]
